apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: kcb
  name: kcb
spec:
  output:
    to:
      kind: ImageStreamTag
      name: kcb:latest
  source:
    contextDir: .
    git:
      uri: https://github.com/burigolucas/kcb.git
      ref: openshift-registry
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Containerfile
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
